cryptoblog/blog/urls.py
from django.urls import re_path
from .views import PostList,PostDetails,PostCreate,CategoryCreate,CategoryDetails,search_results
from .feeds import AtomCategoryFeed,RssCategoryFeed


urlpatterns=[
    re_path(r'^$',PostList.as_view(),name='post_list'),
    re_path(r'^(?P<pk>\d+)/$',PostDetails.as_view(),name='post_details'),
    re_path(r'^create/$',PostCreate.as_view(),name='post_create'),
    re_path(r'categorycreate/$',CategoryCreate.as_view(),name='category_create'),
    re_path(r'^category/(?P<slug>[\w\-]+)/$',CategoryDetails.as_view(),name='category_details'),
    re_path(r'^search/$',search_results,name='search'),
    re_path(r'^category/(?P<category_slug>[\w\-]+)/atom/$',AtomCategoryFeed(),name='atom_category_feed'),
    re_path(r'^category/(?P<category_slug>[\w\-]+)/rss/$',RssCategoryFeed(),name='rss_category_feed'),






]

cryptoblog/cryptoblog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog import urls as blog_urls
from django.views.generic import RedirectView
from news import urls as news_urls
from user import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib.flatpages import views
from blog.feeds import AtomPostFeed,RssPostFeed



sitenews=[
    re_path(r'^atom/$',AtomPostFeed(),name='posts_atom_feed'),
    re_path(r'^rss/$',RssPostFeed(),name='posts_rss_feed')
]


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',RedirectView.as_view(pattern_name='post_list',permanent=False)),
    re_path(r'^blog/',include(blog_urls)),
    re_path(r'^news/',include(news_urls)),
    re_path(r'^user/',include(user_urls,namespace='dj-auth')),
    re_path(r'about/',views.flatpage,{'url':'/about/'},name='about'),
    re_path(r'^sitenews/',include(sitenews)),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG:


    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [re_path(r'^debug/', include(debug_toolbar.urls)), ] + urlpatterns

import mimetypes
mimetypes.add_type("application/javascript", ".js", True)
admin.site.site_header='CoinBlog Admin'

cryptoblog/user/urls.py
from django.urls import re_path,reverse_lazy,include,path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib.auth.forms import AuthenticationForm
from .views import DisableAccount,SignUpView,ActivateAccount,ProfileDetails,ProfileEdit

app_name='user'

password_urls=[
    re_path('^change/$',auth_views.PasswordChangeView.as_view(template_name='user/password_change.html',success_url=reverse_lazy('dj-auth:password_change_done')),name='password_change'),
    re_path(r'^change/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html'),name='password_change_done'),
    re_path(r'^reset/$',auth_views.PasswordResetView.as_view(template_name='user/password_reset.html',email_template_name='user/email_template.txt',subject_template_name='user/subject_template.txt',success_url=reverse_lazy('dj-auth:password_reset_done')),name='password_reset'),
    re_path(r'^reset/sent/$',auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    re_path(r'^reset/'
            r'(?P<uidb64>[0-9A-Za-z-\-])/'
            r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',success_url=reverse_lazy('dj-auth:password_reset_complete')),name='password_reset_confirm'),

    re_path(r'^reset/done/$',auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html',extra_context=AuthenticationForm),name='password_reset_complete'),
]

urlpatterns=[
    re_path(r'^$',RedirectView.as_view(pattern_name='dj-auth:login',permanent=False)),
    re_path(r'^login/$',auth_views.LoginView.as_view(template_name='user/login.html',authentication_form=AuthenticationForm,success_url=reverse_lazy('post_list')),name='login'),
    re_path(r'^logout/$',auth_views.LogoutView.as_view(template_name='user/logout.html',extra_context={'form':AuthenticationForm}),name='logout'),
    re_path(r'^password/',include(password_urls)),
    re_path(r'^disable/$',DisableAccount.as_view(),name='disable_account'),
    re_path(r'^signup/$',SignUpView.as_view(),name='signup'),
    path('activate/<uidb64>/<token>/',ActivateAccount.as_view(),name='activate_account'),
    re_path('^(?P<username>[\w\-]+)/$',ProfileDetails.as_view(),name='profile_details'),
    re_path(r'^(?P<username>[\w\-]+)/edit/$',ProfileEdit.as_view(),name='profile_edit')


]

cryptoblog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
       
        <title>CoinBlog</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- Bootstrap CDN-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/flatly/bootstrap.min.css" integrity="sha384-qF/QmIAj5ZaYFAeQcrQ6bfVMAh4zZlrGwTPY7T/M+iTTLJqJBJjwwnsE5Y0mV7QK" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css" integrity="sha384-7ynz3n3tAGNUYFZD3cWe5PDcE36xj85vyFkawcF6tIwxvIecqKvfwLiaFdizhPpN" crossorigin="anonymous">
        <link rel="alternate" title="Blog Post Atom" type="aplication/rss+xml" href="{% url 'posts_atom_feed'%}">
        <link rel="alternate" title="Blog Post Rss" type="aplication/rss+xml" href="{% url 'posts_rss_feed'%}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" integrity="sha384-EvBWSlnoFgZlXJvpzS+MAUEjvN7+gcCwH+qh7GRFOGgZO0PuwOFro7qPOJnLfe7l" crossorigin="anonymous">

    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'post_list' %}">CoinBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav ms-auto mb-1 mb-lg-1">
                        <li class="nav-item"><a class="nav-link" href="{% url 'post_list' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'news_list' %}">News</a></li>
                        
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}}</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{user.profile.get_absolute_url}}">Profile</a>
                                <a class="dropdown-item" href="{% url 'dj-auth:logout' %}">Log Out</a>
                            </div>
                        </li>

                        {% else %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'dj-auth:login' %}?next={{request.path}}">Log In</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'dj-auth:signup' %}?}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">


                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">

                    {% block content %}
                    {% endblock content %}

                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <form class="d-flex" method="post" action="{% url 'search' %}">
                                {% csrf_token %}
                                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search Post's" name="searched">
                                <button type="submit">Search</button>
                            </form>

                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card boarder-primary mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="{% url 'category_details' 'bitcoin'  %}"><p class="text-primary">Bitcoin</p></a></li>
                                        <li><a href="{% url 'category_details' 'ethereum' %}"><p class="text-primary"> Ethereum</p></a></li>
                                        <li><a href="{% url 'category_details' 'othercoins' %}"><p class="text-primary">Other Coins</p></a></li>
                                        <li><a href="{% url 'category_details' 'nft' %}"><p class="text-primary">NFT's</p></a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="{% url 'category_details' 'defi' %}"><p class="text-primary">DeFi</p></a></li>
                                        <li><a href="{% url 'category_details' 'newprojects' %}"><p class="text-primary">New projects</p></a></li>
                                        <li><a href="{% url 'category_details' 'market' %}"><p class="text-primary">Market</p></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Start Trading</div>
                        <div class="card-body"><a href="http://binance.com/">Binance</a> </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->

        <footer class="py-5 bg-dark">


            <i class="bi bi-rss"> <a href="{% url 'posts_atom_feed' %}" class="feed">Blog Atom Feed</a></i>

            <br>
            <div class="icon">
                <i class="bi bi-rss" >  <a href="{% url 'posts_rss_feed' %}" class="feed">Blog Rss Feed</a></i>

            </div>
            {% block footer %}
            {% endblock footer %}
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; CoinBlog 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
         <script src="https://code.jquery.com/jquery-3.4.1.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
    <script
  src="https://code.jquery.com/jquery-3.6.1.min.js"
  integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
  crossorigin="anonymous"></script>
</html>