cryptoblog/blog/urls.py
from django.urls import re_path
from .views import PostList,PostDetails,PostCreate,CategoryCreate,CategoryDetails,search_results
from .feeds import AtomCategoryFeed,RssCategoryFeed


urlpatterns=[
    re_path(r'^$',PostList.as_view(),name='post_list'),
    re_path(r'^(?P<pk>\d+)/$',PostDetails.as_view(),name='post_details'),
    re_path(r'^create/$',PostCreate.as_view(),name='post_create'),
    re_path(r'categorycreate/$',CategoryCreate.as_view(),name='category_create'),
    re_path(r'^category/(?P<slug>[\w\-]+)/$',CategoryDetails.as_view(),name='category_details'),
    re_path(r'^search/$',search_results,name='search'),
    re_path(r'^category/(?P<category_slug>[\w\-]+)/atom/$',AtomCategoryFeed(),name='atom_category_feed'),
    re_path(r'^category/(?P<category_slug>[\w\-]+)/rss/$',RssCategoryFeed(),name='rss_category_feed'),






]

cryptoblog/cryptoblog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog import urls as blog_urls
from django.views.generic import RedirectView
from news import urls as news_urls
from user import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib.flatpages import views
from blog.feeds import AtomPostFeed,RssPostFeed



sitenews=[
    re_path(r'^atom/$',AtomPostFeed(),name='posts_atom_feed'),
    re_path(r'^rss/$',RssPostFeed(),name='posts_rss_feed')
]


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',RedirectView.as_view(pattern_name='post_list',permanent=False)),
    re_path(r'^blog/',include(blog_urls)),
    re_path(r'^news/',include(news_urls)),
    re_path(r'^user/',include(user_urls,namespace='dj-auth')),
    re_path(r'about/',views.flatpage,{'url':'/about/'},name='about'),
    re_path(r'^sitenews/',include(sitenews)),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG:


    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [re_path(r'^debug/', include(debug_toolbar.urls)), ] + urlpatterns

import mimetypes
mimetypes.add_type("application/javascript", ".js", True)
admin.site.site_header='CoinBlog Admin'

cryptoblog/user/urls.py
from django.urls import re_path,reverse_lazy,include,path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib.auth.forms import AuthenticationForm
from .views import DisableAccount,SignUpView,ActivateAccount,ProfileDetails,ProfileEdit

app_name='user'

password_urls=[
    re_path('^change/$',auth_views.PasswordChangeView.as_view(template_name='user/password_change.html',success_url=reverse_lazy('dj-auth:password_change_done')),name='password_change'),
    re_path(r'^change/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html'),name='password_change_done'),
    re_path(r'^reset/$',auth_views.PasswordResetView.as_view(template_name='user/password_reset.html',email_template_name='user/email_template.txt',subject_template_name='user/subject_template.txt',success_url=reverse_lazy('dj-auth:password_reset_done')),name='password_reset'),
    re_path(r'^reset/sent/$',auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    re_path(r'^reset/'
            r'(?P<uidb64>[0-9A-Za-z-\-])/'
            r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',success_url=reverse_lazy('dj-auth:password_reset_complete')),name='password_reset_confirm'),

    re_path(r'^reset/done/$',auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html',extra_context=AuthenticationForm),name='password_reset_complete'),
]

urlpatterns=[
    re_path(r'^$',RedirectView.as_view(pattern_name='dj-auth:login',permanent=False)),
    re_path(r'^login/$',auth_views.LoginView.as_view(template_name='user/login.html',authentication_form=AuthenticationForm,success_url=reverse_lazy('post_list')),name='login'),
    re_path(r'^logout/$',auth_views.LogoutView.as_view(template_name='user/logout.html',extra_context={'form':AuthenticationForm}),name='logout'),
    re_path(r'^password/',include(password_urls)),
    re_path(r'^disable/$',DisableAccount.as_view(),name='disable_account'),
    re_path(r'^signup/$',SignUpView.as_view(),name='signup'),
    path('activate/<uidb64>/<token>/',ActivateAccount.as_view(),name='activate_account'),
    re_path('^(?P<username>[\w\-]+)/$',ProfileDetails.as_view(),name='profile_details'),
    re_path(r'^(?P<username>[\w\-]+)/edit/$',ProfileEdit.as_view(),name='profile_edit')


]

cryptoblog/user/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractBaseUser,PermissionsMixin,BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import reverse




class Profile(models.Model):
    '''class to create profile objects vconected to user objects'''

    user=models.OneToOneField(User,on_delete=models.CASCADE)
    email_confirmed=models.BooleanField(default=False)
    name=models.CharField(max_length=64)
    username=models.CharField(max_length=64)
    about=models.TextField()
    facebook_profile=models.URLField(max_length=254)
    linkedin_profile=models.URLField(max_length=254)
    twitter_profile=models.URLField(max_length=254)
    profile_image=models.ImageField(upload_to='user_images',blank=True)



    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('dj-auth:profile_details',kwargs={'username':self.username})

    def get_update_url(self):
        return reverse('dj-auth:profile_update',kwargs={'username':self.username})


@receiver(post_save,sender=User)
def update_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()

cryptoblog/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class SignUpForm(UserCreationForm):
    '''class to construct a sign up form'''

    first_name=forms.CharField(max_length=30,required=False)
    last_name=forms.CharField(max_length=30,required=False)
    email=forms.EmailField(max_length=254)

    class Meta:
        model=User
        fields=['username','first_name','last_name','email','password1','password2']


class ProfileForm(forms.ModelForm):
    '''Class to create a form for profile objects'''

    class Meta:
        model=Profile
        fields=['name','about','facebook_profile','linkedin_profile','twitter_profile']

cryptoblog/user/views.py
from django.contrib.auth import get_user,logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect,render,get_object_or_404
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .tokens import account_acctivation_token
from .forms import SignUpForm,ProfileForm
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes,force_str
from .models import Profile




class DisableAccount(View):
    '''Class to disable a user account'''

    success_url=settings.LOGIN_REDIRECT_URL
    template_name='user/disable_account.html'

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self,request):
        return TemplateResponse(request,self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self,request):
        user=get_user(request)
        user.set_unusable_password()
        user.is_active=False
        user.save()
        logout(request)
        return redirect(self.success_url)


class SignUpView(View):
    '''Class to create a view for sign up process'''

    form_class=SignUpForm
    template_name='user/signup.html'

    def get(self,request,*args,**kwargs):
        return render(request,self.template_name,{'form':self.form_class()})

    def post(self,request,*args,**kwargs):
        bound_form=self.form_class(request.POST)
        if bound_form.is_valid():
            user=bound_form.save(commit=False)
            user.is_active=False
            user.save()
            Profile.objects.update_or_create(user=user,defaults={'username':user.get_username()})
            current_site=get_current_site(request)
            subject='Activate you CoinBlog account'
            message=render_to_string('user/account_activation_email.html',
                                     {
                                         'user':user,
                                         'domain':current_site.domain,
                                         'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                                         'token':account_acctivation_token.make_token(user)
                                     })
            user.email_user(subject,message)
            messages.success(request,'Please confirm your email to complete the registration process')
            return redirect('dj-auth:login')
        else:
            return render(request,self.template_name,{'form':bound_form})



class ActivateAccount(View):
    '''Class to activate account bassed on the email link'''

    def get(self,request,uidb64,token,*args,**kwargs):
        try:
            uid=force_str(urlsafe_base64_decode(uidb64))
            user=User.objects.get(pk=uid)
        except (TypeError,ValueError,OverflowError):
            user=None

        if (user != None and account_acctivation_token.check_token(user,token)):
            user.is_active=True
            user.profile.email_confirmed=True
            user.save()
            Profile.objects.update_or_create(user=user,defaults={''})
            return redirect('dj-auth:login')
        else:
            messages.warning(request,'Confirmation link is no longer valid')
            return redirect('dj-auth:signup')



class ProfileDetails(View):
    '''Class to construct a view for profile details'''

    model=Profile
    template_name='user/profile_details.html'

    def get(self,request,username):
        profile=get_object_or_404(self.model,username=username)
        return render(request,self.template_name,{'profile':profile})



class ProfileEdit(View):
    '''Class to construct a view for editing profile objects'''

    model=Profile
    form_class=ProfileForm
    template_name='user/profile_update.html'

    def get(self,request,username):
        profile=get_object_or_404(self.model,username=username)
        form=self.form_class(instance=profile)
        return render(request,self.template_name,{'form':form})

    def post(self,request,username):
        profile=get_object_or_404(self.model,username=username)
        bound_form=self.form_class(request.POST,instance=profile)
        if bound_form.is_valid():
            new_profile=bound_form.save()
            return redirect(new_profile.get_absolute_url())

        else:
            return render(request,self.template_name,{'form':bound_form})

cryptoblog/user/templates/user/base_user.html
{% extends parent_template|default:'base.html' %}

cryptoblog/user/templates/user/disable_account.html
{% extends parent_template|default:'user/base_user.html' %}

{% block content %}
<div class="card mb-4">

<div class="card-body">
    <div class="small text-muted">Disable your account,this acction can not be undone.Are you sure?</div>
    <br>
    <br>
    <form action="{% url 'dj-auth:disable_account' %}"
          method="post">
        {% csrf_token %}
        <button type="submit">Yes</button>
    </form>
    <button class="btn"><a href="{% url 'post_list' %}">No</a> </button>

    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/form_login.html
{% load crispy_forms_tags %}
<form action="{% url 'dj-auth:login' %}"
      method="post">
    {% csrf_token %}
    {{form|crispy}}
    {% if next %}
        <input type="hidden" name="next" value="{{next}}">
    {% endif %}
    <button type="submit">{{login_button|default:'Log In'}}</button>
</form>

cryptoblog/user/templates/user/login.html
{% extends parent_template|default:'user/base_user.html' %}

{% block content %}
<div class="card mb-4">
{% if messages %}
                        {% for message in messages %}
                            <h3>{{message}}</h3>
                        {% endfor %}
                    {% endif %}
    <div class="card-body">
        <div class="small text-muted">Log In Page</div>
        <br>
        <br>
        {% include 'user/form_login.html' %}

    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/logout.html
{% extends parent_template|default:'user/base_user.html' %}

{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Logout Page</div>
        <br>
        <p><em>Successfully loged out</em></p>
        <br>
        {% include 'user/form_login.html' with login_button='Log Back In' %}

    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/password_change.html
{% extends parent_template|default:'user/base_user.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Change Password</div>
        <br>
        <br>
        <form action="{% url 'dj-auth:password_change' %}"
              method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit">Change Password</button>
        </form>

    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/password_change_done.html
{% extends parent_template|default:'user/base_user.html' %}

{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Change Password</div>
        <br>
        <br>
        {% include 'user/form_login.html'%}


    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/password_reset.html
{% extends parent_template|default:'user/base_user.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Password Reset</div>
        <br>
        <br>
        <form action="{% url 'dj-auth:password_reset' %}"
              method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit">Reset My Password</button>
        </form>

    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/password_reset_complete.html
{% extends parent_template|default:'user/base_user.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Password successfully change</div>
        <br>
        <br>
        {% include 'user/form_login.html' %}

    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/password_reset_confirm.html
{% extends parent_template|default:'user/base_user.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">

    <div class="card-body">
        {% if validlink %}
            <div class="small text-muted">Enter a password bellow:</div>
            <br>
            <br>

            <form action="{% url 'dh-auth:password_reset_confirm' %}"
                  method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit">Save New Password</button>
            </form>
        {% else %}
             <div class="small text-muted">Link no longer valid</div>
        <br>
             <div class="small text-muted">Request a new link: <a href="{% url 'dj-auth:password_reset' %}">Here</a> </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/password_reset_done.html
{% extends parent_template|default:'user/base_user.html' %}

{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Please check your email inbox and span folders</div>


    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/profile_details.html
{% extends parent_template|default:'user/base_user.html' %}

{% block content %}

<section class="section profile">
    <div class="row">
        <div class="col-xl-4">
            <div class="card">
                <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                    {% if profile.image %}
                    <img src="" alt="Profile" class="rounded-circle">
                    {% endif %}
                    <h2>{{profile.username}}</h2>
                    <h5>{{profile.job}}</h5>

                    <div class="social-links mt-3">
                        {% if profile.twitter_profile %}
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        {% endif %}
                        {% if profile.facebook_profile %}
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        {% endif %}
                        {% if profile.linkedin_profile %}
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
                <ul class="nav nav-tabs nav-tabs-bordered">
                    <li class="nav-item">
                        <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                    </li>
                </ul>
                <div class="tab-content pt-2">
                    <div class="tab-pane fade show active profile-overview" id="profile-overview">
                        <h5 class="card-title">About</h5>
                        <p class="small fst-italic">{{profile.about}}</p>
                        <h5 class="card-title">Profile Details</h5>
                        <div class="row">
                            <div class="col-lg-3 col-md-4 label ">Name</div>
                            <div class="col-lg-9 col-md-8">{{profile.name}}</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-4 label">Username</div>
                            <div class="col-lg-9 col-md-8">{{profile.username}}</div>
                        </div>
                    </div>
                    <br>
                    <br>
                </div><!-- End Bordered Tabs -->
                {% if user.pk == profile.user.pk %}
                    <button type="button" class="btn btn-outline-dark"><a href="{% url 'dj-auth:profile_edit' profile.username %}">Edit Profile</a> </button>   |   <button type="button" class="btn btn-outline-dark"><a href="{% url 'dj-auth:password_change' %}">Change Password</a> </button> | <button type="button" class="btn btn-outline-dark"><a href="{% url 'dj-auth:disable_account' %}">Delete Account</a> </button>
                {% endif %}
            </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

cryptoblog/user/templates/user/profile_update.html
{% extends parent_template|default:'user/base_user.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Profile Edit</div>
        <br>
        <br>
        <form action="{{profile.get_update_url}}"
        method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit">Save Changes</button>
        </form>

    </div>
</div>
{% endblock content %}

cryptoblog/user/templates/user/signup.html
{% extends parent_template|default:'user/base_user.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">Sign Up</div>
        <br>
        <br>
        <form method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit">Sign Up</button>
        </form>

    </div>
</div>
{% endblock content %}