cryptoblog/blog/urls.py
from django.urls import re_path
from .views import PostList,PostDetails,PostCreate,CategoryCreate,CategoryDetails,search_results
from .feeds import AtomCategoryFeed,RssCategoryFeed


urlpatterns=[
    re_path(r'^$',PostList.as_view(),name='post_list'),
    re_path(r'^(?P<pk>\d+)/$',PostDetails.as_view(),name='post_details'),
    re_path(r'^create/$',PostCreate.as_view(),name='post_create'),
    re_path(r'categorycreate/$',CategoryCreate.as_view(),name='category_create'),
    re_path(r'^category/(?P<slug>[\w\-]+)/$',CategoryDetails.as_view(),name='category_details'),
    re_path(r'^search/$',search_results,name='search'),
    re_path(r'^category/(?P<category_slug>[\w\-]+)/atom/$',AtomCategoryFeed(),name='atom_category_feed'),
    re_path(r'^category/(?P<category_slug>[\w\-]+)/rss/$',RssCategoryFeed(),name='rss_category_feed'),






]

cryptoblog/cryptoblog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog import urls as blog_urls
from django.views.generic import RedirectView
from news import urls as news_urls
from user import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib.flatpages import views
from blog.feeds import AtomPostFeed,RssPostFeed



sitenews=[
    re_path(r'^atom/$',AtomPostFeed(),name='posts_atom_feed'),
    re_path(r'^rss/$',RssPostFeed(),name='posts_rss_feed')
]


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',RedirectView.as_view(pattern_name='post_list',permanent=False)),
    re_path(r'^blog/',include(blog_urls)),
    re_path(r'^news/',include(news_urls)),
    re_path(r'^user/',include(user_urls,namespace='dj-auth')),
    re_path(r'about/',views.flatpage,{'url':'/about/'},name='about'),
    re_path(r'^sitenews/',include(sitenews)),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG:


    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = [re_path(r'^debug/', include(debug_toolbar.urls)), ] + urlpatterns

import mimetypes
mimetypes.add_type("application/javascript", ".js", True)
admin.site.site_header='CoinBlog Admin'

cryptoblog/blog/models.py
from django.db import models
from django.shortcuts import reverse
from taggit.managers import TaggableManager
from django.conf import settings
from django.contrib.auth.models import User


class Category(models.Model):
    '''class to construct a model for category objects'''

    title = models.CharField(max_length=31)
    slug = models.CharField(max_length=31)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('category_details',kwargs={'slug':self.slug})



class Post(models.Model):
    '''Class to construc models for creating post objects'''

    title=models.CharField(max_length=500)
    body=models.TextField()
    date_added=models.DateField(auto_now_add=True)
    tag=TaggableManager()
    image=models.ImageField(upload_to='blog_images')

    category=models.ForeignKey(Category,on_delete=models.CASCADE)



    class Meta:
        ordering=['-date_added',]
        get_latest_by='date_added'


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_details',kwargs={'pk':self.pk})

    def get_update_url(self):
        return reverse('post_update',kwargs={'pk':self.pk})

    def get_delete_url(self):
        return reverse('post_delete',kwargs={'pk':self.pk})

    def get_comment_url(self):
        return reverse('comment_create',kwargs={'pk':self.pk})

    def format_title(self):
        return self.title.title()

    def short_text(self):
        if len(self.body) > 20:
            short=''.join(self.body.split()[:20])
            short+='....'
        else:
            return self.body
        return short







class Answer(models.Model):
    '''Class to construct models for creating answer objects'''

    body=models.TextField()

    date_added=models.DateField(auto_now_add=True)
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)


    class Meta:
        ordering=('-date_added',)
        get_latest_by='date_added'

    def __str__(self):
        return self.body[:50]



    def get_delete_url(self):
        return reverse('answer_delete',kwargs={'pk1':self.post.pk,'pk2':self.pk})

cryptoblog/blog/forms.py
from django import forms
from .models import Post,Answer,Category
from django.core.exceptions import ValidationError


class PostFrom(forms.ModelForm):
    '''Class to create a form for post objects'''

    class Meta:
        model=Post
        fields=['title','body','tag','image','category']

    def clean_title(self):
        title=self.cleaned_data['title'].lower()
        dissallowed=['create','edit','delete']
        if title in dissallowed:
            return ValidationError('post title can not be {title}'.format(title=title))
        return title


class CommentForm(forms.ModelForm):
    '''Class to create a form for answer objects'''

    def __init__(self,*args,**kwargs):
        super(CommentForm,self).__init__(*args,**kwargs)
        self.fields['body'].label=False

    class Meta:
        model=Answer
        fields=['body']



class CategoryForm(forms.ModelForm):
    '''class to create category forms'''

    class Meta:
        model=Category
        fields='__all__'

cryptoblog/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Answer,Category
from .forms import PostFrom,CommentForm,CategoryForm
from django.views.generic import View
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib.auth.decorators import login_required,permission_required
from django.utils.decorators import method_decorator
from user.decorators import class_login_required,class_permission_required


class PostList(View):
    '''Class to construct a view for list of post objects'''

    model=Post
    template_name='blog/post_list.html'
    page_kwargs='page'
    paginated_by=2

    def get(self,request):

        post_list=self.model.objects.all().order_by('-date_added')
        paginator=Paginator(post_list,self.paginated_by)
        page_number=request.GET.get(self.page_kwargs)
        try:
            page=paginator.page(page_number)
        except PageNotAnInteger:
            page=paginator.page(1)
        except EmptyPage:
            page=paginator.page(paginator.num_pages)

        if page.has_previous():
            previous_page_url="?{pkw}={n}".format(pkw=self.page_kwargs,n=page.previous_page_number())
        else:
            previous_page_url=None

        if page.has_next():
            next_page_url="?{pkw}={n}".format(pkw=self.page_kwargs,n=page.next_page_number())
        else:
            next_page_url=None

        context={
            'is_paginated':page.has_other_pages(),
            'previous_page_url':previous_page_url,
            'next_page_url':next_page_url,
            'paginator':paginator,
            'post_list':page
        }


        return render(request,self.template_name,context)




class PostDetails(View):
    '''Class to construct a view for details of each post object'''

    model=Post
    template_name='blog/post_details.html'



    def get(self,request,pk):
        post=get_object_or_404(self.model,pk=pk)
        form=CommentForm()
        return render(request,self.template_name,{'post':post,'form':form})

    def post(self,request,pk):
        post=get_object_or_404(self.model,pk=pk)
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.author=self.request.user
            comment.save()
            return redirect(post.get_absolute_url())
        else:
            form=CommentForm()
            return render(request,self.template_name,{'form':form})









@class_permission_required('blog.add_post')
class PostCreate(View):
    '''Class to create views for creating objects'''

    model=Post
    form_class=PostFrom
    template_name='blog/post_create.html'




    def get(self,request):
        return render(request,self.template_name,{'form':self.form_class()})

    def post(self,request):
        bound_form=self.form_class(request.POST,request.FILES)
        if bound_form.is_valid():
            new_post=bound_form.save()

            return redirect(new_post.get_absolute_url())
        else:
            return render(request,self.template_name,{'form':bound_form})




class CategoryCreate(View):
    '''Class to create a view for category objects creation'''

    form_class=CategoryForm
    template_name='blog/create_category.html'

    def get(self,request):
        return render(request,self.template_name,{'form':self.form_class()})

    def post(self,request):
        bound_form=self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save()
            return redirect('post_list')
        else:
            return render(request,self.template_name,{'form':bound_form})



class CategoryDetails(View):
    '''Class to construct a view with all the post objects from a specific category'''

    model=Category
    template_name='blog/category_details.html'
    paginated_by=3
    page_kwargs='page'

    def get(self,request,slug):
        category=get_object_or_404(self.model,slug=slug)
        post_list=Post.objects.filter(category=category)

        paginator=Paginator(post_list,self.paginated_by)
        page_number=request.GET.get(self.page_kwargs)

        try:
            page=paginator.page(page_number)

        except PageNotAnInteger:
            page=paginator.page(1)

        except EmptyPage:
            page=paginator.page(paginator.num_pages)

        if page.has_previous():
            previous_page_url="?{pkw}={n}".format(pkw=self.page_kwargs,n=page.previous_page_number())
        else:
            previous_page_url=None

        if page.has_next():
            next_page_url="?{pkw}={n}".format(pkw=self.page_kwargs,n=page.next_page_number())
        else:
            next_page_url=None

        context={
            'is_paginated':page.has_other_pages(),
            'previous_page_url':previous_page_url,
            'next_page_url':next_page_url,
            'paginator':paginator,
            'category':category,
            'post_list':page,
        }

        return render(request,self.template_name,context)




def search_results(request):
    model=Post
    template_name='blog/search_result.html'
    if request.method == 'POST':
        searched=request.POST['searched']
        if searched:
            post_list=Post.objects.filter(title__icontains=searched)
            return render(request,template_name,{'post_list':post_list})

cryptoblog/blog/templates/blog/blog_base.html
{% extends parent_template|default:'base.html' %}

cryptoblog/blog/templates/blog/category_details.html
{% extends parent_template|default:'blog/blog_base.html' %}
{% block content %}
{% for post in post_list %}
<div class="card mb-4">
    {% if post.image %}
    <img class="card-img-top" src="{{post.image.url}}" alt="..." /></a>
    {% endif %}
    <div class="card-body">
        <div class="small text-muted">{{post.date_added|default:'F jS, Y'}}</div>
        <h2 class="card-title">{{post.title|title}}</h2>
        <p class="card-text">{{post.body|truncatewords:150}}</p>
        <a class="btn btn-primary" href="{{post.get_absolute_url}}">Read more →</a>
    </div>
</div>


<ol class="breadcrumb">
    <li class="breadcrumb-item">Comments: {{post.answer_set.count}}</a></li>
    <li class="breadcrumb-item">Category: {{post.category}} </li>
    <li class="breadcrumb-item">Date Added: {{post.date_added|default:'F jS, Y'}} </li>

</ol>


{% endfor %}
                    <!-- Pagination-->
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            {% if previous_page_url %}
                            <li class="page-item "><a class="page-link" href="{{previous_page_url}}" >Newer</a></li>
                            {% endif %}
                            {% if next_page_url %}
                            <li class="page-item"><a class="page-link" href="{{next_page_url}}">Older</a></li>
                            {% endif %}
                        </ul>
                    </nav>




{% endblock content %}
{% block footer %}
<i class="bi bi-rss"> <a href="{% url 'posts_atom_feed' %}" class="feed">{{category.title}} Atom Feed</a></i>
{% endblock footer %}

cryptoblog/blog/templates/blog/create_category.html
{% extends parent_template|default:'user/base_user.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'category_create' %}"
      method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit">Create Category</button>
</form>
{% endblock content %}

cryptoblog/blog/templates/blog/post_create.html
{% extends parent_template|default:'blog/blog_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'post_create' %}" enctype="multipart/form-data"
      method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-outline-dark">Add</button>
</form>
{% endblock content %}

cryptoblog/blog/templates/blog/post_details.html
{% extends parent_template|default:'blog/blog_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">

    <div class="card-body">
        <div class="small text-muted">{{post.date_added|default:'F jS, Y'}}</div>
        <h2 class="card-title">{{post.title|title}}</h2>
        <p class="card-text">{{post.body}}</p>

    </div>
</div>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="#">Comments: {{post.answer_set.count}} </a></li>
  <li class="breadcrumb-item"><a href="#">Date Posted: {{post.date_added|default:'F jS, Y'}}</a></li>

</ol>
<br>
<br>

<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">Comment's:</h5>
    </div>
</div>
{% for answer in post.answer_set.all %}
<div class="card mb-4">

    <div class="card-body">

        <div class="small text-muted"><h5>{{answer.author}}:</h5></div>
        <br>
        <div class="small text-muted">{{answer.body}}</div>
    </div>
</div>



{% endfor %}
<br>
<br>

<form
      method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn">Leave a comment</button>

</form>


{% endblock content %}

cryptoblog/blog/templates/blog/post_list.html
{% extends parent_template|default:'blog/blog_base.html' %}
{% block content %}
<body>
<div class="card mb-4">
    <h3>{{category.title|title}}</h3>
</div>

{% for post in post_list %}

<div class="card mb-4">
    {% if post.image %}
    <img class="card-body profile-card pt-4 d-flex flex-column align-items-center" src="{{post.image.url}}" alt="..." />
    {% endif %}
    <div class="card-body">
        <div class="small text-muted">{{post.date_added|default:'F jS, Y'}}</div>
        <h2 class="card-title">{{post.title|title}}</h2>
        <p class="card-text">{{post.body|truncatewords:150}}</p>
        <a class="btn " href="{{post.get_absolute_url}}">Read more →</a>
    </div>
</div>
<ol class="breadcrumb">
    <li class="breadcrumb-item">Comments: {{post.answer_set.count}}</a></li>
    <li class="breadcrumb-item">Category: {{post.category}} </li>
    <li class="breadcrumb-item">Date Added: {{post.date_added|default:'F jS, Y'}} </li>

</ol>
<br>
<br>
<br>
<br>



{% endfor %}
                    <!-- Pagination-->
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            {% if previous_page_url %}
                            <li class="page-item "><a class="page-link" href="{{previous_page_url}}" >Newer</a></li>
                            {% endif %}
                            {% if next_page_url %}
                            <li class="page-item"><a class="page-link" href="{{next_page_url}}">Older</a></li>
                            {% endif %}
                        </ul>
                    </nav>
</body>

{% endblock content %}

cryptoblog/blog/templates/blog/search_result.html
{% extends parent_template|default:'blog/blog_base.html' %}

{% block content %}
{% for post in post_list %}
    <div class="card mb-4">
        {% if post.image %}
        <img class="card-img-top" src="{{post.image.url}}" alt="..." />
        {% endif %}
        <div class="card-body">
            <div class="small text-muted">{{post.date_added|default:'F jS, Y'}}</div>
            <h2 class="card-title">{{post.title|title}}</h2>
            <p class="card-text">{{post.body|truncatewords:150}}</p>
            <a class="btn " href="{{post.get_absolute_url}}">Read more →</a>
        </div>
    </div>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Comments: {{post.answer_set.count}}</a></li>
        <li class="breadcrumb-item">Category: {{post.category}} </li>
        <li class="breadcrumb-item">Date Added: {{post.date_added|default:'F jS, Y'}} </li>

    </ol>
{% endfor %}
{% endblock content %}